version: "3"
services: 
    listing-service:
        build: "./listing-service" 
        depends_on: 
            - listing-service-db
        environment: 
            - DB_URI=mysql://root:password@listing-service-db/listings?charset=UTF8
            - PORT=7100
        ports:
            - 7100:7100
        volumes: 
            - ./listing-service:/opt/app
    
    listing-service-db:
        environment: 
            - MYSQL_DATABASE=listings   
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=root 
        image: mysql:latest
        ports: 
            - 0.0.0.0:7200:3306
        volumes: 
            - /opt/database/entrypoint/listing/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - /opt/database/db_data_listings:/var/lib/mysql
    

    users-service:
        build: "./users-service"
        depends_on:
            - users-service-db
        environment: 
            - DB_URI=mysql://root:password@users-service-db/users?charset=UTF8
            - PORT=7101
        ports:
            - 7101:7101
        volumes:
            - ./users-service:/opt/app

    users-service-db:
        environment: 
            - MYSQL_DATABASE=users  
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=root
        image: mysql:latest
        ports: 
            - 0.0.0.0:7201:3306
        volumes: 
            - /opt/database/db_data_users:/var/lib/mysql
            - /opt/database/entrypoint/users/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d    
